<script>
  import { gt as semverGt } from 'semver';

  import MidiEnabled from "./MidiEnabled.svelte";

  import {
    configuration,
  } from "../stores.js";

  let upgradeString = "";

  configuration.subscribe(c => {
    if (c && c.firmwareVersion && window.latestVersion && !window.versionCompared) {
      window.versionCompared = true;
      if(semverGt(window.latestVersion, c.firmwareVersion)) {
        upgradeString = `A new version of the 16n firmware (${window.latestVersion}) is available.`;
      } else {
        upgradeString = "";
      }
    }
  });

  window.latestVersion = "__firmwareversion__"; // generated by rollup
</script>

<style>
  .details {
    flex: 1 0;
  }

  p.device {
    text-align: right;
  }
  span.upgrade {
    display: block;
    margin-top: 5px;
    color: #888;
  } 

</style>
<MidiEnabled>
  <div class="details">
    <!-- <MidiSelector /> -->
    {#if $configuration}
      <p class='device'>
        Connected: <strong>{$configuration.device().name}</strong> running firmware <strong>{$configuration.firmwareVersion}</strong>
        {#if upgradeString.trim() != ""}
        <span class='upgrade'>
          {upgradeString}
          <a href="https://github.com/16n-faderbank/16n/releases/latest">Download</a>
        </span>
        {/if}
      </p>
    {:else}
      <p class='device'>No device connected.</p>
    {/if}
  </div>
</MidiEnabled>
