<script>
  window.debugMode = true;

  import { gt as semverGt } from 'semver';
  import { ConfigurationObject } from "./Configuration.js";
  import { ImportExport } from "./ImportExport.js";
  import { logger } from "./logger.js";
  import { OxionMidi } from "./OxionMidi.js";

  import {
    configuration,
    editConfiguration,
    selectedMidiOutput,
    controllerMightNeedFactoryReset
  } from "./stores.js";

  import Button from "./components/Button.svelte";
  // import DebugConsole from "./components/DebugConsole.svelte";
  import EditMode from './components/EditMode.svelte';
  import MidiContext from "./components/MidiContext.svelte";
  import MidiEnabled from "./components/MidiEnabled.svelte";
  // import MidiSelector from "./components/MidiSelector.svelte";
  import ViewMode from './components/ViewMode.svelte';

  let editMode = false;
  let upgradeString = "";


  configuration.subscribe(c => {
    if (c && c.firmwareVersion && window.latestVersion && !window.versionCompared) {
      window.versionCompared = true;
      if(semverGt(window.latestVersion, c.firmwareVersion)) {
        upgradeString = `A new version of the 16n firmware (${window.latestVersion}) is available.`;
      } else {
        upgradeString = "";
      }
    }
  })

  function handleMessage(message) {
    switch (message.detail.name) {
      case "toggleEditMode":
        toggleEditMode();
        break;
      case "transmitConfig":
        transmitConfig();
        break;
      case "requestConfig":
        OxionMidi.requestConfig($selectedMidiOutput);
        break;
      case "importConfig":
        ImportExport.import($editConfiguration, $configuration, editConfiguration);
        break;
      case "exportConfig":
        ImportExport.export($configuration);
        break;
      case "transmitFactoryReset":
        transmitFactoryReset();
        break;
      default:
        break;
    }
  }

  function toggleEditMode() {
    editMode = !editMode;
    if (editMode) {
      let oldConfig = ConfigurationObject.clone($configuration);
      editConfiguration.update(c => oldConfig);
    }
  }

  function transmitConfig() {
    let sysexArray = $editConfiguration.toSysexArray();
    logger("Sending sysex:", sysexArray);

    OxionMidi.sendConfiguration($editConfiguration, $selectedMidiOutput);

    $configuration = $editConfiguration;

    editMode = !editMode;
  }

  function transmitFactoryReset() {
    logger("Sending factory reset request");
    editMode = false;
    OxionMidi.sendFactoryResetRequest($selectedMidiOutput);
    setTimeout(() => {
      OxionMidi.requestConfig($selectedMidiOutput);
    }, 50);
  }

  window.latestVersion = "__firmwareversion__"; // generated by rollup
</script>

<style>


  #head {
    margin-bottom: 1rem;
    border-bottom: 1px solid #ccc;
    display: flex;
  }

  #head h1 {
    flex: 1 0;
    margin: 0 0 2rem;
  }

  #head .details {
    flex: 1 0;
  }

  p.device {
    text-align: right;
  }

  main {
    width: 75%;
    margin: 0 auto;
    min-width: calc(16*75px);
    /* background: #fff; */
  }

  #foot {
    font-size: 80%;
    border-top: 1px solid #ccc;
    padding-top: 5px;
    display: flex;
  }

  .foot-left {
    flex: 1;
  }

 span.upgrade {
   display: block;
   margin-top: 5px;
   color: #888;
 } 
</style>

<MidiContext>
  <main>
    <div id="head">
      <h1>16n configuration tool</h1>
      <MidiEnabled>
        <div class="details">
          <!-- <MidiSelector /> -->
          {#if $configuration}
            <p class='device'>
              Connected: <strong>{$configuration.device().name}</strong> running firmware <strong>{$configuration.firmwareVersion}</strong>
              {#if upgradeString.trim() != ""}
              <span class='upgrade'>
                {upgradeString}
                <a href="https://github.com/16n-faderbank/16n/releases/latest">Download</a>
              </span>
              {/if}
            </p>
          {:else}
            <p class='device'>No device connected.</p>
          {/if}
        </div>
      </MidiEnabled>
    </div>
    <MidiEnabled fallback="WebMIDI could not be enabled. Please use a web browser that supports WebMIDI, such as Google Chrome.">
      {#if $configuration}
        {#if editMode}
          <EditMode on:message={handleMessage}></EditMode>
        {:else}
          <ViewMode on:message={handleMessage}></ViewMode> 
        {/if}
        <p />
      {:else}
        {#if $controllerMightNeedFactoryReset}
          <p>It looks like a 16n is trying to connect, but may have a corrupt memory.</p>
          <Button label="Click to reset your 16n's EEPROM to factory defaults" clickMessageName="transmitFactoryReset" on:message={handleMessage}></Button>
        {:else}
          <p>Connect a controller via USB.</p>
        {/if}
      {/if}
    </MidiEnabled>
    <div id="foot">
      <div class='foot-left'>
        16n Editor v{"__buildversion__"}
      </div>
    </div>
  </main>

</MidiContext>
