<script lang="ts">
  /* global __FIRMWARE_VERSION__ */
  import { gt as semverGt } from "semver";

  import { webMidiEnabled } from "$lib/stores";

  import { deviceForId } from "$lib/configuration";
  import { configuration } from "$lib/stores";
  import { onDestroy } from "svelte";

  let upgradeString = $state("");
  let upgradeUrl = $state("");
  // let latestVersion = __FIRMWARE_VERSION__; // generated by vite.config.ts
  let versionCompared = false;

  const unsub = configuration.subscribe((c) => {
    if (c && c.firmwareVersion && c.deviceId && !versionCompared) {
      versionCompared = true;
      const device = deviceForId(c.deviceId);
      if (
        device.latestFirmwareVersion &&
        semverGt(device.latestFirmwareVersion, c.firmwareVersion)
      ) {
        upgradeString = `A new version of the ${device.name} firmware (${device.latestFirmwareVersion}) is available.`;
        upgradeUrl = device.firmwareUrl || "";
      } else {
        upgradeString = "";
        upgradeUrl = "";
      }
    }
  });

  onDestroy(() => {
    unsub();
  });
</script>

{#if $webMidiEnabled}
  <div class="details">
    <!-- <MidiSelector /> -->
    {#if $configuration}
      <p class="device">
        Connected: <strong>{deviceForId($configuration.deviceId).name}</strong>
        running firmware
        <strong>{$configuration.firmwareVersion}</strong>
        {#if upgradeString.trim() != ""}
          <span class="upgrade">
            {upgradeString}
            <a href={upgradeUrl}>Download</a>
          </span>
        {/if}
      </p>
    {:else}
      <p class="device">No device connected.</p>
    {/if}
  </div>
{/if}

<style>
  .details {
    flex: 1 0;
  }

  p.device {
    text-align: right;
  }
  span.upgrade {
    display: block;
    margin-top: 5px;
    color: #888;
  }
</style>
